### ISSUE TITLE
Feature: Toggle Visual Indicator Window

### ISSUE THREAD

**Issue by 12-VidE** [grassbl8d/flexible-pomo-obsidian#13]
Since this version is a more "flexible" plugin, it'll be nice if you can **toggle the opening of the stopwatch window** when a session start. The statusbar indicator is enough for me; closing the visual indicator window is just an inconvenience.

**Comment by grassbl8d** [comment]
Hi,

There's a setting currently for this. You can disable it to note use the the visual indicator.

Thanks!

<img width="955" alt="image" src="https://user-images.githubusercontent.com/93050/159143845-4b76e74c-2b36-403d-b91b-4509b1e9d2c9.png">

**Comment by 12-VidE** [comment]
How can I be that blind?! Thanks
