### ISSUE TITLE
Set Duration Before Starting Pomodoro

### ISSUE THREAD

**Issue by oliwang** [grassbl8d/flexible-pomo-obsidian#15]
Love your plugin. I feel really motivated whenever I see the detailed logs generated after each session.

I was wondering if it's possible to add the option to set duration each time I use "Start Pomodoro" command? Currently, I have to go to options and change the Pomodoro time field. I may have different sessions that require different focus time throughout the day and I don't want to click settings, flexible pomodoro to change the duration each time.

**Comment by grassbl8d** [comment]
Ok thanks 

I will do it this weekend.

Thanks!

**Comment by oliwang** [comment]
Thank you. Looking forward to this feature!

**Comment by grassbl8d** [comment]
Please see 0.6.0

Thanks.
